# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        path: miri-main

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.6'

    - name: create directory
      run: |
        mkdir -p ../miri-main/src/cmd/server/dashboard
        touch ../miri-main/src/cmd/server/dashboard/.gitkeep


    - name: Build-Server
      working-directory: miri-main
      run: go build -trimpath -ldflags '-s -w' -o miri-server ./src/cmd/server/main.go

    - name: Test
      working-directory: miri-main
      run: go test ./...
